
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_nantes_electricity'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_nantes_electricity'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_nantes_electricity:
    # Couche Staging : Typage (Vues)
    staging:
      +materialized: view
      +schema: staging

    # Couche Intermediate : Calculs intermédiaires (Vues)
    intermediate:
      +materialized: view
      +schema: intermediate

    # Couche Marts : Tables finales (Tables)
    marts:
      +materialized: table
      +schema: mart
      # Aexport CSV :
      mart_consommation_horaire:
        +post-hook: "COPY {{ this }} TO 'consommation_horaire_oneshot.csv' (HEADER, DELIMITER ',')"

seeds:
  dbt_nantes_electricity:
    +config:
      # Si des colonnes manquent sur certaines lignes, mets du NULL et avance
      external_options:
        null_padding: true
        ignore_errors: true
